### ISSUE TITLE
Add tag `font` into arrays `phrasingContent` and `flowContent`. 

### ISSUE THREAD

**Issue by denisano** [Simbiat/nl2tag#1]
It seems there should be tag `font` in constant arrays `phrasingContent` and `flowContent`. 

As result the code:
```
<font color="red">Some test phrase in first line</font> 
Second line
```

is like this:
```
<font color="red">Some test phrase in first line</font>Second line
```

but it should be like this:
```
<p><font color="red">Some test phrase in first line</font></p>
<p>Second line</p>
```

**Comment by Simbiat** [comment]
`font` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) in HTML5, so will not be including it by default. If you are still using it in a live environment you can use `setPhrasingContent(['font'])` and/or `setFlowgContent(['font'])` to add it tot he list(s) before processing the text.

**Comment by denisano** [comment]
> `font` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) in HTML5, so will not be including it by default. If you are still using it in a live environment you can use `setPhrasingContent(['font'])` and/or `setFlowgContent(['font'])` to add it tot he list(s) before processing the text.

Thank you for the quick reply. Got it! 
There are still a lot of sites having wysiwyg editors that generate the `<font>` tag. In some cases it is not easy to get rid of `<font>`. 
The `setPhrasingContent(['font'])` and `setFlowgContent(['font'])` have solved the problem.

**Comment by Simbiat** [comment]
Glad, that helped.
Indeed, some old code can still use `font` and other deprecated tags. There can also be custom tags, that need to be treated as phrasing and/or flow content. That's why I added functionality to expand the default lists.

Closing the issue.
